language: python
sudo: false

env:
  global:
    # Doctr deploy key for NSLS-II/PyXRF
    - secure: "ZYRymELlWT6UQNEU4M57jEWfHGy+e04OBEqbhzLiJMc1LBAOKyBlQrGDloYC0mg6C6TtLhVqqxiiYQFDi4aPRxu9iBRcD4dloIZiEBXXn0DAVWmEj2n7rsORyGxbWbEnhyAkyKSu1pfzVUAPZqpXnfRKTqW2rI/9GG4cG0i7B5zP3uL8kT1dji0L9zWB9MMdZygOyPaqlJlHJ/OicWhKcqZYMuxh1D3o4VzYhjuaEctoEWNm8T+NhQehwL9uEEoUHwjm1pIIEul7O2T9Sn0X6+A5+qpUPPKwFd3M4O1QNkGbdNxZxBy4Kd5WfdsVveOQIM4YIHdQ97xbtigFLNVSjdwaUiI2YCuyGWPNyQGP0ak3qxlVqVC4yM5Wo7NPefPXwGi/dyGyTzKdD+4Z4+9vLMgKVXOIZCiUDHZBbEtHEs5Rf33O8WRKvwz3WxsT6FJz+2YfnTCCBv6NFqvduYyE9T1E3RxZR97EA5Vw+B53VHvvhakjTTlXIwIAES81oV489Wz6nbtER4QRuJK89vs4Gn8l9tQ8K48p3vM3ezbUcaek7/fLF2zca+P7Riys0mHMPie5gmBlsM5t7In9eYhv4sQpKvFRoL/NbP29npdeO0ev4QV0mH1OJTWogcDeTnLiIcHYaCpynT5cC8Qfq73PAy1D/Y6AGMjI2iSkWdm7+qQ="

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache

matrix:
  fast_finish: true
  include:
    - python: 2.7
    - python: 3.6
      env: BUILD_DOCS=1
    - python: nightly
  allow_failures:
    - python: nightly

script:
- |
  if [ $BUILD_DOCS ]; then
    pip install -r docs-requirements.txt
    set -e  # If any of the following steps fail, just stop at that point.
    make -C doc html  # Build the documentation.
    doctr deploy --built-docs doc/_build/html .  # Publish the documentation.
  fi
