language: python
sudo: false

env:
  global:
    # Doctr deploy key for NSLS-II/PyXRF
    - secure: "B2JCv1KacvaAr4MIVBbrfuX0Oa/J8GCOhH3oDM02y7zP3hAFbHBKMmA6afhC0xaEf25S9HPfHcJYysDzppmgDUbo8Z20pj0H7+LVQXpjNNxxlEnMk1xLIrSGNq9mEjJTwxdCoHkWHxP4Jouoz9Aa7URFLMAfXbiIItngbTcnsOtyyPduk01QVycrfd/ZsBs/wdDf8szJfGP/o73M50QA3hpbvzYBLOzs+VsVJgojLDoKBSIzkX3Mps7oDxrrwiY+PI9QwBXN7erGg3dg+WUgvCOC//Wk6HeQwxK6OEvGI512o5g/XFp6Wm4veqfgsPxyFGB8sERzOw2ftGP2UAMnCpF3QFql36kXbeoh9GLV7sfkrQSUnonnqM8wU1uwaSiKlHUuvtaIRWbFw0KUUf3JKkZAt21hnKc28A1Q9tjK+a06a51+WjHXb0d0SwbYhkHahk5x++MC70sHGmc0DWVkeHYT4cR/mbogcITrkcoAWDTemN3z4W6bJw+vLhXJ7SKU7AF2d+uMDppN579lB/BB1coOs07EMK1ottWKTYuCu9e+lzECMdSNsmkBp4E5TiStnaassW+ZK23HJ85nx3pPbBMlVnTkCCjCL/cB22IN+z+Ibgq0BOtgMjqRk9sChv+Zb7fCQ7xWbsBRMR4k4CJ6rFu75VKHh+0j6c/VzIx04Gw="

cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.cache/matplotlib"

matrix:
  fast_finish: true
  include:
    - python: 2.7
    - python: 3.6
      env: BUILD_DOCS=1
    - python: nightly
  allow_failures:
    - python: nightly

script:
- |
  if [ $BUILD_DOCS ]; then
    pip install -r docs-requirements.txt
    pushd doc
    make html
    popd
    # Publish docs.
    doctr deploy --deploy-repo NSLS-II/NSLS-II.github.io --deploy-branch-name master PyXRF
  fi
