package:
  name: pyxrf
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: ../

build:
  number: 0

  # Note that this will override the default build string with the Python
  string: {{ environ.get('GIT_BUILD_STR', '') }}_py{{ py }}

  entry_points:
    - pyxrf = pyxrf.gui:run

requirements:
  build:
    - python
    - enaml
    - numpy
    - six

  run:
    - python
    - matplotlib
    - enaml
    - scikit-xray
    - dataportal

test:
  imports:
    - pyxrf
